---
- name: check if exist apache
  command: which httpd
  ignore_errors: True
  register: check_apache

# Apacheのインストール
- include: install.yml
  when: check_apache|failed

- name: enable apache
  service: name=httpd enabled=yes
